try{
    const resultado = 10 / 0
}
 catch(erro) {
    console.error("ocorreu um erro:", erro.message)
 }